CREATE TABLE COMPANY
(
  name VARCHAR(128) NOT NULL,
  id INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE GROUP
(
  name VARCHAR(128) NOT NULL,
  stanOrder INT NOT NULL,
  id INT NOT NULL,
  PRIMARY KEY (stanOrder),
  FOREIGN KEY (id) REFERENCES COMPANY(id)
);